import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [results, setResults] = useState('');

  const fireAPI = async () => {
    console.log('calling API...');
    const response = await axios.get('https://52893-thepipeline.vercel-support.app/api/mail');
    console.log({response})

    setResults(`${Date.now()} - ${JSON.stringify(response.data)}\r\n${results}`)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.trigger}>
          <button onClick={fireAPI}>
            Call API
          </button>
        </p>

        <textarea className={styles.results} value={results} readOnly/>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
